version: '2'
services:
  fusion-release:
    build: .
    environment:
      - BUILDKITE
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_URL
      - BUILDKITE_API_TOKEN
      - GITHUB_TOKEN
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
